[package]
name = "try-rust"
version = "0.1.0"
authors = ["LeFredd <frederic@les-tilleuls.coop>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
